#!/bin/sh
#
# @name mk-u25 Multirotor SITL
#
# @type Multirotor
#
# @maintainer Julian Oes <julian@oes.ch>
#

. ${R}etc/init.d/rc.mc_defaults

param set-default CA_ROTOR_COUNT 12
param set-default CA_ROTOR0_PX 1.005
param set-default CA_ROTOR0_PY 0
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX -1.005
param set-default CA_ROTOR1_PY 0
param set-default CA_ROTOR1_KM -0.05
param set-default CA_ROTOR2_PX -0.566
param set-default CA_ROTOR2_PY 0.801
param set-default CA_ROTOR2_KM 0.05
param set-default CA_ROTOR3_PX 0.566
param set-default CA_ROTOR3_PY -0.801
param set-default CA_ROTOR3_KM -0.05
param set-default CA_ROTOR4_PX 0.566
param set-default CA_ROTOR4_PY 0.801
param set-default CA_ROTOR4_KM -0.05
param set-default CA_ROTOR5_PX -0.566
param set-default CA_ROTOR5_PY -0.801
param set-default CA_ROTOR5_KM 0.05
param set-default CA_ROTOR6_PX 1.005
param set-default CA_ROTOR6_PY 0
param set-default CA_ROTOR6_KM -0.05
param set-default CA_ROTOR7_PX -1.005
param set-default CA_ROTOR7_PY 0
param set-default CA_ROTOR7_KM 0.05
param set-default CA_ROTOR8_PX -0.566
param set-default CA_ROTOR8_PY 0.801
param set-default CA_ROTOR8_KM -0.05
param set-default CA_ROTOR9_PX 0.566
param set-default CA_ROTOR9_PY 0.801
param set-default CA_ROTOR9_KM 0.05
param set-default CA_ROTOR10_PX 0.566
param set-default CA_ROTOR10_PY -0.801
param set-default CA_ROTOR10_KM 0.05
param set-default CA_ROTOR11_PX -0.566
param set-default CA_ROTOR11_PY -0.801
param set-default CA_ROTOR11_KM -0.05


param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106
param set-default PWM_MAIN_FUNC7 107
param set-default PWM_MAIN_FUNC8 108
param set-default PWM_MAIN_FUNC9 109
param set-default PWM_MAIN_FUNC10 110
param set-default PWM_MAIN_FUNC11 111
param set-default PWM_MAIN_FUNC12 112
